GET http://localhost:4200

###

GET http://localhost:4200/books/?title=test

###

POST http://localhost:4200/books
Content-Type: application/json

{
    "title": "Hello World!",
    "price": 1000,
    "isActive": true
}